name: ArcadeFFA
description: ${description}
version: '${version}'
main: org.drappula.arcadeFfa.ArcadeFFA
api-version: '1.21.11'
load: POSTWORLD
authors: [ drappula, TejasLamba2006 ]
dependencies:
  server:
    ArcadeCore:
      load: BEFORE
      required: true
      join-classpath: true
