name: ArcadeFFA
description: ${description}
version: '${version}'
main: org.drappula.arcadeFfa.ArcadeFFA
load: POSTWORLD
authors: [ drappula, TejasLamba2006 ]
depend: [ ArcadeCore ]
commands:
  ffa:
    description: Free For All
    usage: /ffa [join|leave]
